language: csharp
solution: RecamanSequenceGenerator.sln
mono: none
dist: xenial
dotnet: 2.2
script:
 - dotnet build
 - dotnet test --collect:"XPlat Code Coverage"
 - bash <(curl -s https://codecov.io/bash)
